name: handle new issue
on:
  workflow_dispatch:
  issues:
    types: opened
    
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v2.0.2
      with:
        webhook-url: ${{ secrets.ISSUE_WEBHOOK }}
        content: "<@&859525500393357353>, A new issue was Opened on github\nURL: https://github.com/israpps/HDL-Batch-installer/issues/${{ github.event.issue.number }}"
